import Head from "next/head";
import Link from "next/link";
import Date from "../components/date";
import { getSortedPostsData } from "../lib/posts";

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}
export default function Home({ allPostsData }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-5xl md:text-6xl">
          Muhammed / Contigen, welcome to Next.js
        </h1>
        <h3 className="text-3xl md:text-4xl">
          Read{" "}
          <Link href="/posts/first-post">
            <a>first page!</a>
          </Link>
        </h3>
      </main>
      <section className="m-7">
        <h3 className="text-3xl md:text-4xl m-0 my-7">Blog</h3>
        <ul>
          {allPostsData.map(({ id, date, title }) => (
            <li key={id} className="text-2xl ">
              <Link href={`/posts/${id}`}>
                <a className="text-teal-700">{title}</a>
              </Link>
              <br></br>
              <Date dateString={date} />
              <small></small>
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
}
