import Head from "next/head";
import Link from "next/link";
import Date from "../components/date";
import { getSortedPostsData } from "../lib/posts";

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}
export default function Home({ allPostsData }) {
  return (
    <div>
      <Head>
        <title>A Blog App with Nex.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-4xl md:text-5xl">
          Muhammed / Contigen, welcome to Next.js
        </h1>
        <span className="m-7 text-2xl md:text-3xl">
          Read{" "}
          <Link href="/posts/first-post">
            <a className="text-blue-500">first page!</a>
          </Link>
        </span>
      </main>
      <section className="m-7">
        <h3 className="m-0 my-7 text-2xl md:text-3xl">Blog, yes?</h3>
        <ul>
          {allPostsData.map(({ id, date, title }) => (
            <li key={id} className="text-2xl ">
              <Link href={`/posts/${id}`}>
                <a className="text-blue-500">{title}</a>
              </Link>
              <br></br>
              <small>
                <Date dateString={date} />
              </small>
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
}
